### PR TITLE
Fixes #504 query removed on user is back to front page

### LINKED ISSUE #504: Remove query when user gets back to homepage
**Actual Behaviour**

When a user types a query results are displayed. Now when user goes back to homepage - query still persist to be there. To reproduce this bug- type any query and then click on 'back' option in browser. It will redirect to susper's homepage with the same query. 

**Expected Behaviour**

There should not be any query in search bar when returned back to homepage. It should be empty search bar and follow similar to Google.

**Screenshots of the issue**

screenshot from 2017-06-17 17-18-31

screenshot from 2017-06-17 17-19-06

### PR DESCRIPTION
**Pull request by nikhilrayaprolu**
Fixes issue #504 now query is removed when user is back to homepage.

Demo Link: https://nikhilrayaprolu.github.io/susper.com-1/

### CODE REVIEW

File: src/app/index/index.component.ts [hunk 1]
```diff
@@ -19,7 +22,9 @@ export class IndexComponent implements OnInit {
     timezoneOffset: 0
   };
   constructor(private route: ActivatedRoute,
-              private router: Router ) { }
+              private router: Router, private store: Store<fromRoot.State> ) {
+    this.store.dispatch(new queryactions.QueryAction(''));
+  }
```
Comment (harshit98) [inline src/app/index/index.component.ts]: Kindly indent the code properly :)

**Comment by nikhilrayaprolu** [comment]
@harshit98 @Marauderer97 kindly review now.indented the code

**Comment by nikhilrayaprolu** [comment]
@Marauderer97 done.
