### PR TITLE
Fixes #464, Images are being displayed

### LINKED ISSUE #464: Images are not showing up on image search
While image search works on the host yacy system (http://yacy.searchlab.eu/yacysearch.html?query=trump&maximumRecords=10&resource=global&verify=ifexist&prefermaskfilter=&cat=href&constraint=&contentdom=image) it does not work on susper.

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes issue #464 

Changes: Images are being displayed in Susper.

Demo Link: [Here](https://marauderer97.github.io/susper.com/)

Screenshots for the change: 

image

### CODE REVIEW

**Comment by Marauderer97** [comment]
@harshit98 @nikhilrayaprolu @isuruAb @sandeepm96

File: src/app/results/results.component.ts [hunk 1]
```diff
@@ -81,7 +81,7 @@ export class ResultsComponent implements OnInit {
   }
 
   imageClick() {
-    this.getPresentPage(0);
+    this.getPresentPage(1);
     this.resultDisplay = 'images';
```
Comment (harshit98) [inline src/app/results/results.component.ts]: I think `this.getPresentPage(0)` was added to solve pagination issues which we were facing earlier. Kindly explain.

Comment (Marauderer97) [inline src/app/results/results.component.ts]: The pagination bar used two kinds of indexing earlier, one was zero based for pages less than 4 and the other was one based for pages > 4, recently we modified the function and its calls to have just one kind of indexing so that it is cleaner and easier to understand, hence we need to update the indexing here too . Hope this helps make it clear :)
