### PR TITLE
Fixes #204,Fixed scroll position to top on routing

### LINKED ISSUE #204: Links to About Page not to top of Page
Opening About Page does not open to top of page.

### PR DESCRIPTION
**Pull request by Marauderer97**
Fixes #204, Runs a script in the main app component, to always scroll to top of the page, when a new route is loaded

### CODE REVIEW

File: src/app/app.component.ts [hunk 1]
```diff
@@ -7,4 +8,13 @@ import { Component } from '@angular/core';
 })
 export class AppComponent {
   title = 'Susper';
+  constructor(private router: Router) { }
+  ngOnInit() {
+    this.router.events.subscribe((evt) => {
+      if (!(evt instanceof NavigationEnd)) {
```
Comment (nikhilrayaprolu) [inline src/app/app.component.ts]: there could be a case when it is not at the end of the navigation,(somewhere in the middle). this should work in those cases too.

Comment (Marauderer97) [inline src/app/app.component.ts]: @nikhilrayaprolu I am not sure what you mean. This event is triggered, once a navigation action completes successfully. And will get triggered wherever I chose to change the route.
image
